[2021-07-14 18:18:36,606] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bdt_2021_ETL.create_db_4 2021-07-14T18:16:59.219967+00:00 [queued]>
[2021-07-14 18:18:36,644] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: bdt_2021_ETL.create_db_4 2021-07-14T18:16:59.219967+00:00 [queued]>
[2021-07-14 18:18:36,646] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 18:18:36,647] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-07-14 18:18:36,648] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 18:18:36,716] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): create_db_4> on 2021-07-14T18:16:59.219967+00:00
[2021-07-14 18:18:36,724] {standard_task_runner.py:52} INFO - Started process 925 to run task
[2021-07-14 18:18:36,730] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'bdt_2021_ETL', 'create_db_4', '2021-07-14T18:16:59.219967+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/second_dag.py', '--cfg-path', '/tmp/tmpmg36l6un', '--error-file', '/tmp/tmpwafrihye']
[2021-07-14 18:18:36,731] {standard_task_runner.py:77} INFO - Job 31: Subtask create_db_4
[2021-07-14 18:18:36,868] {logging_mixin.py:104} INFO - Running <TaskInstance: bdt_2021_ETL.create_db_4 2021-07-14T18:16:59.219967+00:00 [running]> on host bf600838264e
[2021-07-14 18:18:37,146] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bdt_2021_ETL
AIRFLOW_CTX_TASK_ID=create_db_4
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T18:16:59.219967+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-14T18:16:59.219967+00:00
[2021-07-14 18:18:37,176] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2021-07-14 18:18:37,177] {base.py:78} INFO - Using connection to: id: mysql_test_conn. Host: 172.17.0.1, Port: 3310, Schema: project_bdt, Login: root, Password: ***, extra: {}
[2021-07-14 18:18:37,191] {dbapi.py:204} INFO - Running statement: CREATE TABLE `rper14` ( `nquest` INT NOT NULL, 
`nord` INT NOT NULL, 
`y` FLOAT NOT NULL), parameters: None
[2021-07-14 18:18:37,278] {dbapi.py:212} INFO - Rows affected: 0
[2021-07-14 18:18:37,281] {python.py:151} INFO - Done. Returned value was: None
[2021-07-14 18:18:37,327] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=bdt_2021_ETL, task_id=create_db_4, execution_date=20210714T181659, start_date=20210714T181836, end_date=20210714T181837
[2021-07-14 18:18:37,433] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-14 18:18:37,465] {local_task_job.py:151} INFO - Task exited with return code 0
